[CLOUD-159] Attach docker-registry-secret as IPS for RabbitMQ cluster to not compete with Kyverno
Ubix/ubix-charts pull request #150
Opened 2024-03-19 21:58 UTC by matheusraz

2024-03-19 22:08 UTC, batimeunnescafe approved these changes

2024-03-19 22:13 UTC, jfmrm requested changes

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/account-provisioner.yaml
> +    name: rabbitmq-backoffice
this should be a dynamic name that should match the cluster name

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/account-provisioner.yaml
> +    name: rabbitmq-backoffice
this should be dynamically created with a map.

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/account-provisioner.yaml
> +    name: {{ .Values.rabbitmqClusterName }}
each user should have it's own set of permissions

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/account-status.yaml
> +  destinationType: queue
all these resources should be dynamically created using maps

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/cluster-secret.yaml
> +      namespace: databases
let's change the cluster secret to be a kyverno cluster policy

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/policies.yaml
> +    name: {{ .Values.rabbitmqClusterName }}
policies should be dynamically created using maps. This one can be one default

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/rabbitmq.yaml
> +    effect: NoSchedule
these tolerations should be configuratble.

2024-03-19 22:13 UTC, jfmrm commented on charts/rabbitmq/templates/rabbitmq.yaml
> +  - name: docker-registry-secret
this should be configurable

2024-03-20 17:09 UTC, jfmrm requested changes

2024-03-20 17:09 UTC, jfmrm commented on charts/rabbitmq/templates/cluster-secret.yaml
let's ditch cluster secret. Let's use kyverno instead

2024-03-20 17:09 UTC, jfmrm commented on charts/rabbitmq/templates/policies.yaml
> +{{ range .Values.policies }}
is this expecting a list?

would be better if we expect a map. It's better to compose configuration.

2024-03-20 17:09 UTC, jfmrm commented on charts/rabbitmq/templates/queue-exchanges.yaml
> +{{ end }}
same for all of these... let's use maps to allow better configuration composition

2024-03-20 17:09 UTC, jfmrm commented on charts/rabbitmq/templates/user-permission.yaml
> +{{ end }}
same here. Let's use maps

2024-03-20 17:09 UTC, jfmrm commented on charts/rabbitmq/templates/rabbitmq.yaml
> +  - name: docker-registry-secret
for image pull secrets let's make it configurable and make this the default value.

2024-03-20 17:11 UTC, jfmrm requested changes

2024-03-20 17:11 UTC, jfmrm commented on charts/rabbitmq/templates/rabbitmq.yaml
> +    effect: NoSchedule
let's also make tolerations customizable

2024-03-20 17:12 UTC, jfmrm commented on charts/rabbitmq/templates/rabbitmq.yaml
> +    effect: NoSchedule
and set this one as the default.

2024-03-21 19:23 UTC, jfmrm requested changes

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/cluster-secret.yaml
> +  name: sync-secret
this name needs to have some kind of variable sulfix and/or prefix. Otherwise it will conflict with multiple installations of the chart.

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/cluster-secret.yaml
> +        name: {{ $userName }}-user-credentials
also needs more then this to template the name to avoid conflicts

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/cluster-secret.yaml
> +            name: {{ $userName }}-user-credentials
also needs more then this to template the name to avoid conflicts

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/policies.yaml
> +  name: {{ $clusterName }}-{{ $key }}
also needs more then this to template the name to avoid conflicts

maybe {{ .Release.name }}?

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/queue-exchanges.yaml
> +  name: {{ $clusterName }}-{{ $queueName }}
also needs more then this to template the name to avoid conflicts

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/queue-exchanges.yaml
> +  name: {{ $clusterName }}-{{ $exchangeName }}
also needs more then this to template the name to avoid conflicts

2024-03-21 19:23 UTC, jfmrm commented on charts/rabbitmq/templates/queue-exchanges.yaml
> +  name: {{ $clusterName }}-{{ $exchangeName }}
also needs more then this to template the name to avoid conflicts

2024-03-21 20:06 UTC, jfmrm approved these changes

2024-03-21 20:06 UTC, merged