feat: add s3 bucket and policies to composition
Ubix/ubix-charts pull request #24
Opened 2023-03-27 17:53 UTC by hugo-calado

2023-04-03 16:55 UTC, jfmrm requested changes
General comments:
- if you patch a field, add it to the spec even if it's empty or with a fake value like "patchme", it will improve readability.
- add patches in the order that the fields appear in the spec, from top to bottom, it will also improve readability.
- You will probably need to define one bucket policy and acl per bucket.

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +  - name: bucket
this name should be descriptive, since it should be unique across the composition

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +            resolve: "always"
remove these lines.

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.forProvider.region
explicit patch type

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: "%s-%s-%s-name"
what is the purpose of this bucket?

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +            resolve: "always"
remove these lines.

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.forProvider.region
explicit the patch type.

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: "%s-%s-%s-name"
name can be `solution-space-backend`

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +              #name: childaccount
avoid using these selectors, for our use case it will be too messy to rely on labels for this, reather use the `ToCompositeFieldPach` to output the id of the bucket into the composite on the bucket definition, and here you will be able to pick that value up and inject as a `FromCompositeFieldPatch`.

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.forProvider.region
explicit patch types

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +              #name: childaccount
use bucket instead of bucketSelector

2023-04-03 16:55 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.forProvider.region
explicit patch types

2023-04-03 19:28 UTC, hugo-calado commented on charts/child-account-composition/templates/composition.yaml
> +  - name: bucket
@jfmrm On the setup there is no name it onsly 's3', that's why it is just 'bucket'
![image](https://user-images.githubusercontent.com/120131620/229607777-db4e2827-37d3-4949-8640-960b1333892a.png)

2023-04-03 20:09 UTC, hugo-calado commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: "%s-%s-%s-name"
not sure, maybe @nelscata knows

2023-04-04 14:14 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +  - name: bucket
can u check the name given to it inside the terragrunt.hcl file?

2023-04-04 14:15 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: "%s-%s-%s-name"
@nelscata can u give us some clarity? :D

2023-04-04 14:17 UTC, jfmrm requested changes

2023-04-04 14:17 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +              #name: childaccount
up

2023-04-04 17:39 UTC, hugo-calado commented
TODO: define 'bucket' name and update composition and definition resources accordingly

2023-04-17 18:34 UTC, jfmrm requested changes
almost 100% there.
The problem is only in the name. We can alter the external name using the annotation `   crossplane.io/external-name: some-custom-name`. Let's keep the `metadata.name` following the pattern of `<id>-solution-space-backend` and use the region

2023-04-17 18:34 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          - fromFieldPath: spec.id
I think u meant to use the account id here right? should be status.id

2023-04-17 18:34 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: metadata.name
add here some formatting so the resource name is descriptive like `<spec.id>-solution-space-backend`

2023-04-28 14:17 UTC, jfmrm requested changes

2023-04-28 14:17 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: metadata.name
we should keep the name of the kubernetes resource consistent inly with `<id>-solution-space-backend`, let's add one more patch to add an annotation to alter the external name https://docs.crossplane.io/v1.10/concepts/managed-resources/#external-name.

This should follow the same pattern as what @nelscata named for the longhorn Bucket.

2023-05-08 14:10 UTC, jfmrm requested changes

2023-05-08 14:10 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +    - type: CombineFromComposite
should be From Composite Field path

2023-05-08 14:10 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          crossplane.io/external-name: solution-space-backend-bucket
```
     - type: CombineFromComposite
        combine:
          variables:
            - fromFieldPath: spec.id
            - fromFieldPath: status.id
            - fromFieldPath: spec.parameters.region
          strategy: string
          string:
            fmt: '%s-%s-%s-longhorn-backups'
        toFieldPath: metadata.annotations['crossplane.io/external-name']
```

2023-06-27 15:27 UTC, closed without merging