Add new subnets, routes and nat-gateway
Ubix/ubix-charts pull request #94
Opened 2023-12-18 18:51 UTC by tianomagdaong

2023-12-18 20:06 UTC, jfmrm requested changes

2023-12-18 20:06 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: 'private-%s-1-1c'
```suggestion
          fmt: '%s-nat-gateway-1'
```

2023-12-18 20:06 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.providerConfigRef.name
no need for new routes

2023-12-18 20:06 UTC, jfmrm commented on charts/child-account-composition/templates/composition.yaml
> +        string:
no need for new routes

2023-12-19 09:53 UTC, tianomagdaong commented on charts/child-account-composition/templates/composition.yaml
> +      fromFieldPath: status.atProvider.id
added new routetable-private-1 for the new nat-gateway. removed new public route-table

2023-12-19 09:53 UTC, tianomagdaong commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: 'private-%s-1-1c'
done.

2023-12-19 09:53 UTC, tianomagdaong commented on charts/child-account-composition/templates/composition.yaml
> +      toFieldPath: spec.providerConfigRef.name
Done.

2023-12-19 09:54 UTC, tianomagdaong commented on charts/child-account-composition/templates/composition.yaml
> +        string:
Retain new private-route for the new nat-gateway.

2023-12-19 10:13 UTC, tianomagdaong commented on charts/child-account-composition/templates/composition.yaml
> +          fmt: 'public-%s-1a'
done.

2023-12-19 12:02 UTC, jfmrm approved these changes

2023-12-19 15:58 UTC, merged